version: "3.5"

services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: sh -c "cp -f prod.env .env && php artisan migrate && php -S api:8000 -t public"
    restart: always
    depends_on:
      - db
    networks:
      - app-network
    container_name: api

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql-data:/var/lib/mysql:rw
    networks:
      - app-network
volumes:
  mysql-data:

#Docker Networks
networks:
  app-network:
    driver: bridge
